### PR TITLE
Allow toggle between light/dark mode separate from theme

### PR DESCRIPTION
**Pull request by michael-pratt**
Proposed solution for Issue #85 (this replaces closed PR #87).

### CODE REVIEW

**Review by bric3 — APPROVED** [review]
Looks good to me.

**Comment by bric3** [comment]
Sorry for the late feedback, thanks for the changes !

**Comment by LintaoAmons** [comment]
How to toggle the light mode?

**Comment by michael-pratt** [comment]
> How to toggle the light mode?

There is a new button on the editor window to toggle it. I don't believe a new version has been released with this change, however, so you'll need to build off main.

**Comment by LintaoAmons** [comment]
Thanks~ I'll try

**Pull request merged**
