### PR TITLE
Allow toggle between light/dark mode separate from theme

### PR DESCRIPTION
**Pull request by michael-pratt**
Regarding #85 , here is a proposed solution to allow toggling the editor window between light and dark mode separate from the UI theme.

### CODE REVIEW

**Comment by bric3** [comment]
Thank you so much for the contribution!
I'll look at it later as I'm on holiday!

Thank you !

**Comment by bric3** [comment]
Ah note I was refactoring the code this summer but I have a racy issue (around file save) I didn't have time to figure out at this time, this may prevent a release when this or gets merged.

**Comment by michael-pratt** [comment]
No worries, thanks for the response and let me know if the code needs any changes when you are ready to merge!

**Comment by michael-pratt** [comment]
FYI, I moved the changes for this off of `main` and onto their own branch so this PR is obsolete. Will open a new PR shortly.

**Pull request closed without merging**
